# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f65bd48f0dd68590940e1f7d8dc02d4c0c8e011a3f4884506af6a63903dee19ea889238c53101af15232196d28531d4d8ce3d9abcfeccfb9cafec88357e0b5ee

test:
  secret_key_base: 68f2680778b9a10f53f33487cfdab378a58719bf9ff9443b1c4e0f69bc7833fa4fca3e2f3cddcb1d43c955bd2d3f5dc23a21a554f09082aa5865f3860a50c137

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
